### PR TITLE
Add play 2.5 support

### PR DESCRIPTION
**Pull request by johannegger**
— maybe publish it with a suffix?

### CODE REVIEW

**Comment by pedrorijo91** [comment]
there's already one branch for play 2.5.x (https://github.com/codacy/play-tomcatcp/commits/play-25). Is something wrong with that one?

**Comment by johannegger** [comment]
@mrfyda unfortunately i realised too late that you already created a branch for play-2.5. Let me know if you want to go forward with yours, then we can just close this one here. 
Just an info: mine is demoted from a play-app to an sbt library that depends on play-libs only (no play-sbt-plugin) & I separated scala and java sources.

**Comment by mrfyda** [comment]
Cherry pick a49f66b to this branch

**Comment by pedrorijo91** [comment]
merge/decline on this ?

**Pull request closed without merging**
